# Generated by Django 4.2.7 on 2023-12-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_accesorio_coche_usuario_eleccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('entregado', 'Entregado'), ('camino', 'Camino'), ('fabricacion', 'Fabricacion')], default='fabricacion', max_length=11)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='shop.eleccion')),
            ],
        ),
    ]
