# Generated by Django 4.2.7 on 2023-12-04 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('apellidos', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('ciudad', models.CharField(max_length=100, null=True)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('metodo_pago', models.CharField(choices=[('contra_reembolso', 'Contra reembolso'), ('tarjeta', 'Tarjeta')], default='contra_reembolso', max_length=20)),
                ('status', models.CharField(choices=[('entregado', 'Entregado'), ('camino', 'Camino'), ('fabricacion', 'Fabricacion')], default='fabricacion', max_length=11)),
                ('id_pedido', models.CharField(editable=False, max_length=36, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
