# Generated by Django 5.0 on 2023-12-05 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('valoracion', models.IntegerField(choices=[(1, 'Una estrella'), (2, 'Dos estrellas'), (3, 'Tres estrellas'), (4, 'Cuatro estrellas'), (5, 'Cinco estrellas')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
